Repository Ssergiomc/ExpensesManager_CaCPython_24155G8_Front, pull requests merged in 2024-05, with the labels that each got.

#1 update readme
  README.md
Labels: documentation

#6 Minor changes
  README.md
  assets/images/Abacus_35794.ico
  index.html
Labels: documentation, enhancement

#8 Improve seo fix home scroll
  assets/images/apple-touch-icon.png
  assets/images/maskable_icon_x192.png
  index.html
  js/app.js
  manifest.json
  manifestdark.json
  robots.txt
  sitemap.xml
  styles/components/home.css
Labels: bug, enhancement

#9 Agregado de dashboard
  README.md
  components/Dash.html
  config/componentConfig.js
  styles/components/dash.css
Labels: documentation, enhancement

#11 Fixing add dash minor errors
  README.md
  components/Dash.html
  components/Gasto.html
  config/componentConfig.js
  styles/components/dash.css
  styles/components/gasto.css
  styles/index.css
Labels: bug, documentation, help wanted, wontfix

#12 Dash working
  components/Dash.html
  config/componentConfig.js
  index.html
  styles/components/dash.css
  styles/index.css
Labels: enhancement

#13 Migueprueba
  .gitignore
  assets/images/control-gastos.jpg
  assets/images/control-gastos.png
  assets/images/facebook.png
  assets/images/favicon
  assets/images/icono-usuario.png
  assets/images/instagram.png
  assets/images/x.png
  formulario.html
  login.html
  styles/styles.css
  validacion.js
Labels: enhancement, good first issue

#14 Adapt register
  assets/images/control-gastos.jpg
  assets/images/extra/control-gastos.png
  assets/images/facebook.png
  assets/images/favicon
  assets/images/icono-usuario.png
  assets/images/instagram.png
  assets/images/x.png
  components/Registro.html
  formulario.html
  login.html
  styles/components/registro.css
  styles/index.css
  styles/main-basic-components.css
  styles/main-variables.css
  styles/styles.css
  validacion.js
Labels: enhancement

#16 Fixing navbar closing menu
  assets/images/logo_wallet_color_resized.png
  components/Login.html
  components/Navbar.html
  config/componentConfig.js
  index.html
  js/app.js
  styles/components/gasto.css
  styles/components/navbar.css
Labels: bug, enhancement

#17 Improve seo behaviour
  assets/images/abacus.png
  assets/images/extra/coins-1726618_1280.jpg
  assets/images/extra/coins-1726618_1280.webp
  assets/images/extra/control-gastos.png
  assets/images/extra/control-gastos.webp
  assets/images/extra/money-2724241_640.jpg
  assets/images/extra/money-2724241_640.webp
  assets/images/extra/team-spirit-2447163_640.jpg
  assets/images/extra/team-spirit-2447163_640.webp
  components/Footer.html
  components/Gasto.html
  components/Login.html
  components/Navbar.html
  components/Registro.html
  components/Test.html
  index.html
  manifest.json
  manifestdark.json
  styles/components/home.css
  styles/components/navbar.css
Labels: enhancement

#18 update robots+index SEO tags
  index.html
  robots.txt
Labels: enhancement

#19 test netlify forms
  components/Gasto.html
Labels: enhancement

#21 update not display form netlify+create router path form success+comp …
  components/FormSuccess.html
  components/Gasto.html
  router.js
Labels: enhancement

#23 Images readme
  assets/images/screenshots/dash.png
  assets/images/screenshots/errorpage.png
  assets/images/screenshots/gasto_dark.png
  assets/images/screenshots/gasto_light.png
  assets/images/screenshots/register.png
  assets/images/screenshots/responsive.png
  assets/images/screenshots/stats.png
  assets/images/screenshots/successform.png
Labels: documentation

#24 update create contact form with validation+netlify form recognition+s…
  components/Contacto.html
  config/componentConfig.js
  styles/components/contacto.css
Labels: enhancement

#26 update adding g search console
  google175bc607507e2e6a.html
Labels: enhancement
